language: python
python:
  - "2.7"

install:
  - pip install coverage
  - pip install green codecov
  - pip install .

script:
  - dimspy --help
  - green -vvv --run-coverage

after_script:
  - python -m codecov
